project/config/routes.rb
Rails.application.routes.draw do
  resources :order_products do
    collection do
      get 'choose'
      get 'update_address'
    end
  end
  resources :orders do
    member do
      post 'pass'
      post 'receive'
    end
  end
  get "/shipping_infos/new_index", to: "shipping_infos#new_index",as:"new_index_shipping_infos"
  post "/shipping_infos/create_index", to: "shipping_infos#create_index",as:"create_index_shipping_infos"
  resources :shipping_infos do
    # collection do
    #  post 'new_index'
    #end
  end
  resources :carts
  resources :favorites
  #root :to => 'products#read'
  get 'products/read', to: 'products#read', as: 'products_read'
  #post 'products/:product_id/addfav', to: 'products#addfav', as: 'addfav_product'
  resources :products do
    member do
      get 'more'
      post 'addfav'
    end
  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users do
  end
  #devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users,except: [:show,:destroy,:update]
  # Defines the root path route ("/")
  # root "articles#index"
end

project/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  #belongs_to :shipping_info
  #belongs_to :user
  #belongs_to :shipping_info
  has_many :order_products,dependent: :destroy
  has_many :products,through: :order_products,source: :products
end

project/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /orders or /orders.json
  def index
    puts "Request format: #{request.format}"
    puts "Parameters: #{params.inspect}"
    if current_user.has_role? :god
     @orders = if params[:status]
                            Order.where(status: params[:status])
                          else
                            Order.all
                          end
    else
      @orders = if params[:status]
                  current_user.orders.where(status: params[:status])
                else
                  current_user.orders.all
                end
    end
    respond_to do |format|
      format.html
      format.js
    end
    end
  def pass
    @order = Order.find(params[:id])
    respond_to do |format|
    if @order.update(status:"sending")
      format.html { redirect_to orders_path, notice: "Order was successfully updated." }
      format.json { render :show, status: :ok, location: @order }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @order.errors, status: :unprocessable_entity }
    end
    end
  end
  def receive
    @order = Order.find(params[:id])
    respond_to do |format|
    if @order.update(status:"finished")
      format.html { redirect_to orders_path, notice: "Order was successfully updated." }
      format.json { render :show, status: :ok, location: @order }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @order.errors, status: :unprocessable_entity }
    end
    end
  end
  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    total = 0
    @order = Order.new
    @products = Product.find(session[:product_ids].split(","))
    @shipping_info = ShippingInfo.find(session[:selected_shipping_info])
    @order.receiver = @shipping_info.receiver
    @order.address = @shipping_info.address
    @order.phone_number = @shipping_info.phone_number
    @order.postal_code = @shipping_info.postal_code
    @order.user = current_user
    @order.status = "waiting pass"
    @products.each do |product|
      num = Cart.where(user: current_user, product: product).first.quantity
      price = product.price
      total = total +price*num
      @order.order_products.new(product:product,quantity:
        num)
    end
    @order.total = total
    respond_to do |format|
      if @order.save
        @products.each do |product|
          num = Cart.where(user: current_user, product: product).first.quantity
          sales = product.sales+num
          while(true)
            if product.update(sales:sales)
              break
            else
              sleep(1)
            end
          end
          current_user.cart_products.destroy(product)
        end
        format.html { redirect_to products_read_path, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:user_id, :shipping_info_id, :status, :total,:product_ids)
    end
end

project/app/helpers/orders_helper.rb
module OrdersHelper
end

project/app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :shipping_info_id, style: "display: block" %>
    <%= form.text_field :shipping_info_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project/app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>User:</strong>
    <%= order.user_id %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= order.id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= order.total %>
  </p>

</div>

project/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

project/app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= form_with( url: orders_path, method: :get,id: "order_index", local: false )do |form| %>
  <%= form.label :status %>
  <%= form.collection_check_boxes :status, [['Waiting Pass', 'waiting pass'], ['Sending', 'sending'], ['Finished', 'finished']], :last, :first %>
  <%= form.submit 'Filter' %>
<% end %>
<%if  not current_user.has_role? :god %>
<%= link_to "back to products", products_read_path %>
  <%else %>
  <%= link_to "back to products", products_path %>
  <%end %>
<!--<%= link_to "New order", new_order_path %>-->

project/app/views/orders/index.js.erb
$(document).ready(function(){
    var html = '';
    <% @orders.each do |order| %>
    html += "<%= j render order %>" +
      "<p>" +
      "<%= j link_to 'Show this order', order %>" +
      "</p>";
    <% end %>
    $("#orders").html(html);
});

project/app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

project/app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>
<% @order.order_products.each do |order_product| %>
  <%=render order_product %>
<% end %>
<p>
  <strong>Receiver:</strong>
  <%= @order.receiver %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @order.phone_number %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @order.postal_code %>
</p>
<div>
  <!--<%= link_to "Edit this order", edit_order_path(@order) %>--> |
  <%= link_to "Back to orders", orders_path %>
    <%if not current_user.has_role? :god%>
    <%if @order.status == "sending"%>
    <%= button_to "receive order", receive_order_path(@order) %>
      <%end %>
  <%else %>
    <%if @order.status == "waiting pass" %>
  <%= button_to "send order", pass_order_path(@order)%>
      <%end %>
<%end %>
  <%=button_to "destroy",@order,method: :delete %>
    </div>