project/config/routes.rb
Rails.application.routes.draw do
  resources :order_products do
    collection do
      get 'choose'
      get 'update_address'
    end
  end
  resources :orders do
    member do
      post 'pass'
      post 'receive'
    end
  end
  get "/shipping_infos/new_index", to: "shipping_infos#new_index",as:"new_index_shipping_infos"
  post "/shipping_infos/create_index", to: "shipping_infos#create_index",as:"create_index_shipping_infos"
  resources :shipping_infos do
    # collection do
    #  post 'new_index'
    #end
  end
  resources :carts
  resources :favorites
  #root :to => 'products#read'
  get 'products/read', to: 'products#read', as: 'products_read'
  #post 'products/:product_id/addfav', to: 'products#addfav', as: 'addfav_product'
  resources :products do
    member do
      get 'more'
      post 'addfav'
    end
  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users do
  end
  #devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users,except: [:show,:destroy,:update]
  # Defines the root path route ("/")
  # root "articles#index"
end

project/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product

end

project/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /favorites or /favorites.json
  def index
    @favorites = current_user.favorites
  end

  # GET /favorites/1 or /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites or /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully created." }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1 or /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully updated." }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1 or /favorites/1.json
  def destroy
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url, notice: "Favorite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :product_id)
    end
end

project/app/helpers/favorites_helper.rb
module FavoritesHelper
end

project/app/views/favorites/_favorite.html.erb
<div id="<%= dom_id favorite %>">
  <p>
    <strong>Product:</strong>
    <%= render favorite.product %>
  </p>
  <strong>Created:</strong>
  <%= time_ago_in_words(favorite.created_at) %> ago
  </p>
</div>

project/app/views/favorites/_form.html.erb
<%= form_with(model: favorite) do |form| %>
  <% if favorite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
        <% favorite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project/app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render "form", favorite: @favorite %>

<br>

<div>
  <%= link_to "Show this favorite", @favorite %> |
  <%= link_to "Back to favorites", favorites_path %>
</div>

project/app/views/favorites/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Favorites</h1>

<div id="favorites">
  <% @favorites.each do |favorite| %>
    <%= render favorite %>
    <p>
      <%= link_to "Show this product", more_product_path(favorite.product) %>
    </p>
  <% end %>
</div>

<%= link_to "Back to products", products_read_path %>

project/app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render "form", favorite: @favorite %>

<br>

<div>
  <%= link_to "Back to favorites", favorites_path %>
</div>

project/app/views/favorites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @favorite %>

<div>
  <%= link_to "Edit this favorite", edit_favorite_path(@favorite) %> |
  <%= link_to "Back to favorites", favorites_path %>

  <%= button_to "Destroy this favorite", @favorite, method: :delete %>
</div>